### ISSUE TITLE
travis plugin-LdapLogin builds fails due to minimal changes to travisyml.twig template

### ISSUE THREAD

**Issue by nwoetzel** [matomo-org/travis-scripts#29]
I am trying to work on the plugin-LdapLogin
the travis builds fails due to a recent changes in the travis.yml template
https://github.com/piwik/travis-scripts/blob/master/generator/templates/travis.yml.twig

Basically the generated .travis.yml file and the one in the plugin-LoginLdap repo disagree
https://travis-ci.org/piwik/plugin-LoginLdap/jobs/149084931#L318

Although the changes are not revelant for the build (empty line moved, some spacing in the end of the line)

This is the line where the diff is called
https://github.com/piwik/travis-scripts/blob/master/autoupdate_travis_yml.sh#L52

One could probably use some options with diff to ignore additional spaces or new lines
I guess any combination of (copu from man diff):

<pre>
       -Z, --ignore-trailing-space
              ignore white space at line end

       -b, --ignore-space-change
              ignore changes in the amount of white space

       -w, --ignore-all-space
              ignore all white space

       -B, --ignore-blank-lines
              ignore changes whose lines are all blank
</pre>

Will do to be more tolerant with changes to the template that do not have any impact on the function of the .travis.yml script

Thanks a lot

**Comment by sgiehl** [comment]
We discontinued automatic updates to the test file while migrating to github actions. So this issue isn't relevant anymore.
