### ISSUE TITLE
Adjust template to support PHP 8 by default (for plugins)

### ISSUE THREAD

**Issue by tsteur** [matomo-org/travis-scripts#77]
That's in case we keep using Travis. Then we'd need to maybe automatically add to the template PHP 8 and things like https://github.com/innocraft/plugin-LoginSaml/blob/4.x-dev/.travis.yml#L47-L56

**Comment by sgiehl** [comment]
Note: Dropping support for PHP 7.2 would actually make that a lot easier, as the additional code won't be required and everything would work again as is.

**Comment by sgiehl** [comment]
No longer needed. Tests on GitHub actions support PHP 8.
